### ISSUE TITLE
Does this work for y410p?

### ISSUE THREAD

**Issue by jonathansolorzn** [MegaCookie/Lenovo-Y580-OSX-Installer-Clover#1]

**Comment by JesseVelden** [comment]
Nope, I'm sorry! However if you're into coding, you can easily fork and include your own DSDT and Kexts and publish it as a custom installer for your own y410p. I can help you, if you need help with that and want to maintain your installer of course.

**Comment by jonathansolorzn** [comment]
That would be awesome!

**Comment by jonathansolorzn** [comment]
Here's a [gitter.im room](https://gitter.im/feniixx/hackintosh-lenovo-y410p-setup?utm_source=share-link&utm_medium=link&utm_campaign=share-link) to be able to chat:)
